name = "particle"
uuid = "2ec77544-40da-4a53-b61e-922457346676"
authors = ["DaisukeKogure <kogure.d.816@ms.saitama-u.ac.jp>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
